version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # RabbitMQ management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Map local ./rabbitmq_data directory to /var/lib/rabbitmq in container
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}  # Default username
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}  # Default password
volumes:
  rabbitmq_data:
